/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-linode-api/apis/object/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageKeys implements StorageKeyInterface
type FakeStorageKeys struct {
	Fake *FakeObjectV1alpha1
	ns   string
}

var storagekeysResource = schema.GroupVersionResource{Group: "object.linode.kubeform.com", Version: "v1alpha1", Resource: "storagekeys"}

var storagekeysKind = schema.GroupVersionKind{Group: "object.linode.kubeform.com", Version: "v1alpha1", Kind: "StorageKey"}

// Get takes name of the storageKey, and returns the corresponding storageKey object, and an error if there is any.
func (c *FakeStorageKeys) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StorageKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(storagekeysResource, c.ns, name), &v1alpha1.StorageKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageKey), err
}

// List takes label and field selectors, and returns the list of StorageKeys that match those selectors.
func (c *FakeStorageKeys) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StorageKeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(storagekeysResource, storagekeysKind, c.ns, opts), &v1alpha1.StorageKeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StorageKeyList{ListMeta: obj.(*v1alpha1.StorageKeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.StorageKeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageKeys.
func (c *FakeStorageKeys) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(storagekeysResource, c.ns, opts))

}

// Create takes the representation of a storageKey and creates it.  Returns the server's representation of the storageKey, and an error, if there is any.
func (c *FakeStorageKeys) Create(ctx context.Context, storageKey *v1alpha1.StorageKey, opts v1.CreateOptions) (result *v1alpha1.StorageKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(storagekeysResource, c.ns, storageKey), &v1alpha1.StorageKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageKey), err
}

// Update takes the representation of a storageKey and updates it. Returns the server's representation of the storageKey, and an error, if there is any.
func (c *FakeStorageKeys) Update(ctx context.Context, storageKey *v1alpha1.StorageKey, opts v1.UpdateOptions) (result *v1alpha1.StorageKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(storagekeysResource, c.ns, storageKey), &v1alpha1.StorageKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageKey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStorageKeys) UpdateStatus(ctx context.Context, storageKey *v1alpha1.StorageKey, opts v1.UpdateOptions) (*v1alpha1.StorageKey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(storagekeysResource, "status", c.ns, storageKey), &v1alpha1.StorageKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageKey), err
}

// Delete takes name of the storageKey and deletes it. Returns an error if one occurs.
func (c *FakeStorageKeys) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(storagekeysResource, c.ns, name), &v1alpha1.StorageKey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageKeys) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(storagekeysResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StorageKeyList{})
	return err
}

// Patch applies the patch and returns the patched storageKey.
func (c *FakeStorageKeys) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StorageKey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(storagekeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.StorageKey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageKey), err
}
