/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "kubeform.dev/provider-linode-api/client/clientset/versioned"
	domainv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/domain/v1alpha1"
	fakedomainv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/domain/v1alpha1/fake"
	firewallv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/firewall/v1alpha1"
	fakefirewallv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/firewall/v1alpha1/fake"
	imagev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/image/v1alpha1"
	fakeimagev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/image/v1alpha1/fake"
	instancev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/instance/v1alpha1"
	fakeinstancev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/instance/v1alpha1/fake"
	lkev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/lke/v1alpha1"
	fakelkev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/lke/v1alpha1/fake"
	nodebalancerv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/nodebalancer/v1alpha1"
	fakenodebalancerv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/nodebalancer/v1alpha1/fake"
	objectv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/object/v1alpha1"
	fakeobjectv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/object/v1alpha1/fake"
	rdnsv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/rdns/v1alpha1"
	fakerdnsv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/rdns/v1alpha1/fake"
	sshkeyv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/sshkey/v1alpha1"
	fakesshkeyv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/sshkey/v1alpha1/fake"
	stackscriptv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/stackscript/v1alpha1"
	fakestackscriptv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/stackscript/v1alpha1/fake"
	tokenv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/token/v1alpha1"
	faketokenv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/token/v1alpha1/fake"
	userv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/user/v1alpha1"
	fakeuserv1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/user/v1alpha1/fake"
	volumev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/volume/v1alpha1"
	fakevolumev1alpha1 "kubeform.dev/provider-linode-api/client/clientset/versioned/typed/volume/v1alpha1/fake"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// DomainV1alpha1 retrieves the DomainV1alpha1Client
func (c *Clientset) DomainV1alpha1() domainv1alpha1.DomainV1alpha1Interface {
	return &fakedomainv1alpha1.FakeDomainV1alpha1{Fake: &c.Fake}
}

// FirewallV1alpha1 retrieves the FirewallV1alpha1Client
func (c *Clientset) FirewallV1alpha1() firewallv1alpha1.FirewallV1alpha1Interface {
	return &fakefirewallv1alpha1.FakeFirewallV1alpha1{Fake: &c.Fake}
}

// ImageV1alpha1 retrieves the ImageV1alpha1Client
func (c *Clientset) ImageV1alpha1() imagev1alpha1.ImageV1alpha1Interface {
	return &fakeimagev1alpha1.FakeImageV1alpha1{Fake: &c.Fake}
}

// InstanceV1alpha1 retrieves the InstanceV1alpha1Client
func (c *Clientset) InstanceV1alpha1() instancev1alpha1.InstanceV1alpha1Interface {
	return &fakeinstancev1alpha1.FakeInstanceV1alpha1{Fake: &c.Fake}
}

// LkeV1alpha1 retrieves the LkeV1alpha1Client
func (c *Clientset) LkeV1alpha1() lkev1alpha1.LkeV1alpha1Interface {
	return &fakelkev1alpha1.FakeLkeV1alpha1{Fake: &c.Fake}
}

// NodebalancerV1alpha1 retrieves the NodebalancerV1alpha1Client
func (c *Clientset) NodebalancerV1alpha1() nodebalancerv1alpha1.NodebalancerV1alpha1Interface {
	return &fakenodebalancerv1alpha1.FakeNodebalancerV1alpha1{Fake: &c.Fake}
}

// ObjectV1alpha1 retrieves the ObjectV1alpha1Client
func (c *Clientset) ObjectV1alpha1() objectv1alpha1.ObjectV1alpha1Interface {
	return &fakeobjectv1alpha1.FakeObjectV1alpha1{Fake: &c.Fake}
}

// RdnsV1alpha1 retrieves the RdnsV1alpha1Client
func (c *Clientset) RdnsV1alpha1() rdnsv1alpha1.RdnsV1alpha1Interface {
	return &fakerdnsv1alpha1.FakeRdnsV1alpha1{Fake: &c.Fake}
}

// SshkeyV1alpha1 retrieves the SshkeyV1alpha1Client
func (c *Clientset) SshkeyV1alpha1() sshkeyv1alpha1.SshkeyV1alpha1Interface {
	return &fakesshkeyv1alpha1.FakeSshkeyV1alpha1{Fake: &c.Fake}
}

// StackscriptV1alpha1 retrieves the StackscriptV1alpha1Client
func (c *Clientset) StackscriptV1alpha1() stackscriptv1alpha1.StackscriptV1alpha1Interface {
	return &fakestackscriptv1alpha1.FakeStackscriptV1alpha1{Fake: &c.Fake}
}

// TokenV1alpha1 retrieves the TokenV1alpha1Client
func (c *Clientset) TokenV1alpha1() tokenv1alpha1.TokenV1alpha1Interface {
	return &faketokenv1alpha1.FakeTokenV1alpha1{Fake: &c.Fake}
}

// UserV1alpha1 retrieves the UserV1alpha1Client
func (c *Clientset) UserV1alpha1() userv1alpha1.UserV1alpha1Interface {
	return &fakeuserv1alpha1.FakeUserV1alpha1{Fake: &c.Fake}
}

// VolumeV1alpha1 retrieves the VolumeV1alpha1Client
func (c *Clientset) VolumeV1alpha1() volumev1alpha1.VolumeV1alpha1Interface {
	return &fakevolumev1alpha1.FakeVolumeV1alpha1{Fake: &c.Fake}
}
