apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: records.domain.linode.kubeform.com
spec:
  group: domain.linode.kubeform.com
  names:
    kind: Record
    listKind: RecordList
    plural: records
    singular: record
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  domainID:
                    description: The ID of the Domain to access.
                    format: int64
                    type: integer
                  id:
                    type: string
                  name:
                    description: The name of this Record. This field's actual usage
                      depends on the type of record this represents. For A and AAAA
                      records, this is the subdomain being associated with an IP address.
                      Generated for SRV records.
                    type: string
                  port:
                    description: The port this Record points to.
                    format: int64
                    type: integer
                  priority:
                    description: The priority of the target host. Lower values are
                      preferred.
                    format: int64
                    type: integer
                  protocol:
                    description: The protocol this Record's service communicates with.
                      Only valid for SRV records.
                    type: string
                  recordType:
                    description: The type of Record this is in the DNS system. For
                      example, A records associate a domain name with an IPv4 address,
                      and AAAA records associate a domain name with an IPv6 address.
                    type: string
                  service:
                    description: The service this Record identified. Only valid for
                      SRV records.
                    type: string
                  tag:
                    description: The tag portion of a CAA record. It is invalid to
                      set this on other record types.
                    type: string
                  target:
                    description: The target for this Record. This field's actual usage
                      depends on the type of record this represents. For A and AAAA
                      records, this is the address the named Domain should resolve
                      to.
                    type: string
                  ttlSec:
                    description: '''Time to Live'' - the amount of time in seconds
                      that this Domain''s records may be cached by resolvers or other
                      domain servers. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.'
                    format: int64
                    type: integer
                  weight:
                    description: The relative weight of this Record. Higher values
                      are preferred.
                    format: int64
                    type: integer
                required:
                - domainID
                - recordType
                - target
                type: object
              state:
                properties:
                  domainID:
                    description: The ID of the Domain to access.
                    format: int64
                    type: integer
                  id:
                    type: string
                  name:
                    description: The name of this Record. This field's actual usage
                      depends on the type of record this represents. For A and AAAA
                      records, this is the subdomain being associated with an IP address.
                      Generated for SRV records.
                    type: string
                  port:
                    description: The port this Record points to.
                    format: int64
                    type: integer
                  priority:
                    description: The priority of the target host. Lower values are
                      preferred.
                    format: int64
                    type: integer
                  protocol:
                    description: The protocol this Record's service communicates with.
                      Only valid for SRV records.
                    type: string
                  recordType:
                    description: The type of Record this is in the DNS system. For
                      example, A records associate a domain name with an IPv4 address,
                      and AAAA records associate a domain name with an IPv6 address.
                    type: string
                  service:
                    description: The service this Record identified. Only valid for
                      SRV records.
                    type: string
                  tag:
                    description: The tag portion of a CAA record. It is invalid to
                      set this on other record types.
                    type: string
                  target:
                    description: The target for this Record. This field's actual usage
                      depends on the type of record this represents. For A and AAAA
                      records, this is the address the named Domain should resolve
                      to.
                    type: string
                  ttlSec:
                    description: '''Time to Live'' - the amount of time in seconds
                      that this Domain''s records may be cached by resolvers or other
                      domain servers. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.'
                    format: int64
                    type: integer
                  weight:
                    description: The relative weight of this Record. Higher values
                      are preferred.
                    format: int64
                    type: integer
                required:
                - domainID
                - recordType
                - target
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
