apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: domains.domain.linode.kubeform.com
spec:
  group: domain.linode.kubeform.com
  names:
    kind: Domain
    listKind: DomainList
    plural: domains
    singular: domain
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  axfrIPS:
                    description: The list of IPs that may perform a zone transfer
                      for this Domain. This is potentially dangerous, and should be
                      set to an empty list unless you intend to use it.
                    items:
                      type: string
                    type: array
                  description:
                    description: A description for this Domain. This is for display
                      purposes only.
                    type: string
                  domain:
                    description: The domain this Domain represents. These must be
                      unique in our system; you cannot have two Domains representing
                      the same domain.
                    type: string
                  expireSec:
                    description: The amount of time in seconds that may pass before
                      this Domain is no longer authoritative. Valid values are 0,
                      300, 3600, 7200, 14400, 28800, 57600, 86400, 172800, 345600,
                      604800, 1209600, and 2419200 - any other value will be rounded
                      to the nearest valid value.
                    format: int64
                    type: integer
                  group:
                    description: The group this Domain belongs to. This is for display
                      purposes only.
                    type: string
                  id:
                    type: string
                  masterIPS:
                    description: The IP addresses representing the master DNS for
                      this Domain.
                    items:
                      type: string
                    type: array
                  refreshSec:
                    description: The amount of time in seconds before this Domain
                      should be refreshed. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.
                    format: int64
                    type: integer
                  retrySec:
                    description: The interval, in seconds, at which a failed refresh
                      should be retried. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.
                    format: int64
                    type: integer
                  soaEmail:
                    description: Start of Authority email address. This is required
                      for master Domains.
                    type: string
                  status:
                    description: Used to control whether this Domain is currently
                      being rendered.
                    type: string
                  tags:
                    description: An array of tags applied to this object. Tags are
                      for organizational purposes only.
                    items:
                      type: string
                    type: array
                  ttlSec:
                    description: '''Time to Live'' - the amount of time in seconds
                      that this Domain''s records may be cached by resolvers or other
                      domain servers. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.'
                    format: int64
                    type: integer
                  type:
                    description: If this Domain represents the authoritative source
                      of information for the domain it describes, or if it is a read-only
                      copy of a master (also called a slave).
                    type: string
                required:
                - domain
                - type
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  axfrIPS:
                    description: The list of IPs that may perform a zone transfer
                      for this Domain. This is potentially dangerous, and should be
                      set to an empty list unless you intend to use it.
                    items:
                      type: string
                    type: array
                  description:
                    description: A description for this Domain. This is for display
                      purposes only.
                    type: string
                  domain:
                    description: The domain this Domain represents. These must be
                      unique in our system; you cannot have two Domains representing
                      the same domain.
                    type: string
                  expireSec:
                    description: The amount of time in seconds that may pass before
                      this Domain is no longer authoritative. Valid values are 0,
                      300, 3600, 7200, 14400, 28800, 57600, 86400, 172800, 345600,
                      604800, 1209600, and 2419200 - any other value will be rounded
                      to the nearest valid value.
                    format: int64
                    type: integer
                  group:
                    description: The group this Domain belongs to. This is for display
                      purposes only.
                    type: string
                  id:
                    type: string
                  masterIPS:
                    description: The IP addresses representing the master DNS for
                      this Domain.
                    items:
                      type: string
                    type: array
                  refreshSec:
                    description: The amount of time in seconds before this Domain
                      should be refreshed. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.
                    format: int64
                    type: integer
                  retrySec:
                    description: The interval, in seconds, at which a failed refresh
                      should be retried. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.
                    format: int64
                    type: integer
                  soaEmail:
                    description: Start of Authority email address. This is required
                      for master Domains.
                    type: string
                  status:
                    description: Used to control whether this Domain is currently
                      being rendered.
                    type: string
                  tags:
                    description: An array of tags applied to this object. Tags are
                      for organizational purposes only.
                    items:
                      type: string
                    type: array
                  ttlSec:
                    description: '''Time to Live'' - the amount of time in seconds
                      that this Domain''s records may be cached by resolvers or other
                      domain servers. Valid values are 0, 300, 3600, 7200, 14400,
                      28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                      - any other value will be rounded to the nearest valid value.'
                    format: int64
                    type: integer
                  type:
                    description: If this Domain represents the authoritative source
                      of information for the domain it describes, or if it is a read-only
                      copy of a master (also called a slave).
                    type: string
                required:
                - domain
                - type
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
