apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: firewalls.firewall.linode.kubeform.com
spec:
  group: firewall.linode.kubeform.com
  names:
    kind: Firewall
    listKind: FirewallList
    plural: firewalls
    singular: firewall
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  devices:
                    description: The devices associated with this firewall.
                    items:
                      properties:
                        ID:
                          description: The ID of the firewall device.
                          format: int64
                          type: integer
                        entityID:
                          description: The ID of the underlying entity for the firewall
                            device (e.g. the Linode's ID).
                          format: int64
                          type: integer
                        label:
                          description: The label of the underlying entity for the
                            firewall device.
                          type: string
                        type:
                          description: The type of firewall device.
                          type: string
                        url:
                          description: The URL of the underlying entity for the firewall
                            device.
                          type: string
                      type: object
                    type: array
                  disabled:
                    description: If true, the Firewall is inactive.
                    type: boolean
                  id:
                    type: string
                  inbound:
                    description: A firewall rule that specifies what inbound network
                      traffic is allowed.
                    items:
                      properties:
                        action:
                          description: Controls whether traffic is accepted or dropped
                            by this rule. Overrides the Firewall’s inbound_policy
                            if this is an inbound rule, or the outbound_policy if
                            this is an outbound rule.
                          type: string
                        ipv4:
                          description: A list of IP addresses, CIDR blocks, or 0.0.0.0/0
                            (to allow all) this rule applies to.
                          items:
                            type: string
                          type: array
                        ipv6:
                          description: A list of IPv6 addresses or networks this rule
                            applies to.
                          items:
                            type: string
                          type: array
                        label:
                          description: Used to identify this rule. For display purposes
                            only.
                          type: string
                        ports:
                          description: A string representation of ports and/or port
                            ranges (i.e. "443" or "80-90, 91").
                          type: string
                        protocol:
                          description: The network protocol this rule controls.
                          type: string
                      required:
                      - action
                      - label
                      - protocol
                      type: object
                    type: array
                  inboundPolicy:
                    description: The default behavior for inbound traffic. This setting
                      can be overridden by updating the inbound.action property for
                      an individual Firewall Rule.
                    type: string
                  label:
                    description: The label for the Firewall. For display purposes
                      only. If no label is provided, a default will be assigned.
                    type: string
                  linodes:
                    description: The IDs of Linodes to apply this firewall to.
                    items:
                      format: int64
                      type: integer
                    type: array
                  outbound:
                    description: A firewall rule that specifies what outbound network
                      traffic is allowed.
                    items:
                      properties:
                        action:
                          description: Controls whether traffic is accepted or dropped
                            by this rule. Overrides the Firewall’s inbound_policy
                            if this is an inbound rule, or the outbound_policy if
                            this is an outbound rule.
                          type: string
                        ipv4:
                          description: A list of IP addresses, CIDR blocks, or 0.0.0.0/0
                            (to allow all) this rule applies to.
                          items:
                            type: string
                          type: array
                        ipv6:
                          description: A list of IPv6 addresses or networks this rule
                            applies to.
                          items:
                            type: string
                          type: array
                        label:
                          description: Used to identify this rule. For display purposes
                            only.
                          type: string
                        ports:
                          description: A string representation of ports and/or port
                            ranges (i.e. "443" or "80-90, 91").
                          type: string
                        protocol:
                          description: The network protocol this rule controls.
                          type: string
                      required:
                      - action
                      - label
                      - protocol
                      type: object
                    type: array
                  outboundPolicy:
                    description: The default behavior for outbound traffic. This setting
                      can be overridden by updating the outbound.action property for
                      an individual Firewall Rule.
                    type: string
                  status:
                    description: The status of the firewall.
                    type: string
                  tags:
                    description: An array of tags applied to this object. Tags are
                      for organizational purposes only.
                    items:
                      type: string
                    type: array
                required:
                - inboundPolicy
                - label
                - outboundPolicy
                type: object
              state:
                properties:
                  devices:
                    description: The devices associated with this firewall.
                    items:
                      properties:
                        ID:
                          description: The ID of the firewall device.
                          format: int64
                          type: integer
                        entityID:
                          description: The ID of the underlying entity for the firewall
                            device (e.g. the Linode's ID).
                          format: int64
                          type: integer
                        label:
                          description: The label of the underlying entity for the
                            firewall device.
                          type: string
                        type:
                          description: The type of firewall device.
                          type: string
                        url:
                          description: The URL of the underlying entity for the firewall
                            device.
                          type: string
                      type: object
                    type: array
                  disabled:
                    description: If true, the Firewall is inactive.
                    type: boolean
                  id:
                    type: string
                  inbound:
                    description: A firewall rule that specifies what inbound network
                      traffic is allowed.
                    items:
                      properties:
                        action:
                          description: Controls whether traffic is accepted or dropped
                            by this rule. Overrides the Firewall’s inbound_policy
                            if this is an inbound rule, or the outbound_policy if
                            this is an outbound rule.
                          type: string
                        ipv4:
                          description: A list of IP addresses, CIDR blocks, or 0.0.0.0/0
                            (to allow all) this rule applies to.
                          items:
                            type: string
                          type: array
                        ipv6:
                          description: A list of IPv6 addresses or networks this rule
                            applies to.
                          items:
                            type: string
                          type: array
                        label:
                          description: Used to identify this rule. For display purposes
                            only.
                          type: string
                        ports:
                          description: A string representation of ports and/or port
                            ranges (i.e. "443" or "80-90, 91").
                          type: string
                        protocol:
                          description: The network protocol this rule controls.
                          type: string
                      required:
                      - action
                      - label
                      - protocol
                      type: object
                    type: array
                  inboundPolicy:
                    description: The default behavior for inbound traffic. This setting
                      can be overridden by updating the inbound.action property for
                      an individual Firewall Rule.
                    type: string
                  label:
                    description: The label for the Firewall. For display purposes
                      only. If no label is provided, a default will be assigned.
                    type: string
                  linodes:
                    description: The IDs of Linodes to apply this firewall to.
                    items:
                      format: int64
                      type: integer
                    type: array
                  outbound:
                    description: A firewall rule that specifies what outbound network
                      traffic is allowed.
                    items:
                      properties:
                        action:
                          description: Controls whether traffic is accepted or dropped
                            by this rule. Overrides the Firewall’s inbound_policy
                            if this is an inbound rule, or the outbound_policy if
                            this is an outbound rule.
                          type: string
                        ipv4:
                          description: A list of IP addresses, CIDR blocks, or 0.0.0.0/0
                            (to allow all) this rule applies to.
                          items:
                            type: string
                          type: array
                        ipv6:
                          description: A list of IPv6 addresses or networks this rule
                            applies to.
                          items:
                            type: string
                          type: array
                        label:
                          description: Used to identify this rule. For display purposes
                            only.
                          type: string
                        ports:
                          description: A string representation of ports and/or port
                            ranges (i.e. "443" or "80-90, 91").
                          type: string
                        protocol:
                          description: The network protocol this rule controls.
                          type: string
                      required:
                      - action
                      - label
                      - protocol
                      type: object
                    type: array
                  outboundPolicy:
                    description: The default behavior for outbound traffic. This setting
                      can be overridden by updating the outbound.action property for
                      an individual Firewall Rule.
                    type: string
                  status:
                    description: The status of the firewall.
                    type: string
                  tags:
                    description: An array of tags applied to this object. Tags are
                      for organizational purposes only.
                    items:
                      type: string
                    type: array
                required:
                - inboundPolicy
                - label
                - outboundPolicy
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
