apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: nodebalancers.nodebalancer.linode.kubeform.com
spec:
  group: nodebalancer.linode.kubeform.com
  names:
    kind: Nodebalancer
    listKind: NodebalancerList
    plural: nodebalancers
    singular: nodebalancer
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  clientConnThrottle:
                    description: Throttle connections per second (0-20). Set to 0
                      (zero) to disable throttling.
                    format: int64
                    type: integer
                  created:
                    description: When this NodeBalancer was created.
                    type: string
                  hostname:
                    description: This NodeBalancer's hostname, ending with .nodebalancer.linode.com
                    type: string
                  id:
                    type: string
                  ipv4:
                    description: The Public IPv4 Address of this NodeBalancer
                    type: string
                  ipv6:
                    description: The Public IPv6 Address of this NodeBalancer
                    type: string
                  label:
                    description: The label of the Linode NodeBalancer.
                    type: string
                  region:
                    description: The region where this NodeBalancer will be deployed.
                    type: string
                  tags:
                    description: An array of tags applied to this object. Tags are
                      for organizational purposes only.
                    items:
                      type: string
                    type: array
                  transfer:
                    description: Information about the amount of transfer this NodeBalancer
                      has had so far this month.
                    items:
                      properties:
                        in:
                          description: The total transfer, in MB, used by this NodeBalancer
                            this month
                          format: double
                          type: number
                        out:
                          description: The total inbound transfer, in MB, used for
                            this NodeBalancer this month
                          format: double
                          type: number
                        total:
                          description: The total outbound transfer, in MB, used for
                            this NodeBalancer this month
                          format: double
                          type: number
                      type: object
                    type: array
                  updated:
                    description: When this NodeBalancer was last updated.
                    type: string
                required:
                - region
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  clientConnThrottle:
                    description: Throttle connections per second (0-20). Set to 0
                      (zero) to disable throttling.
                    format: int64
                    type: integer
                  created:
                    description: When this NodeBalancer was created.
                    type: string
                  hostname:
                    description: This NodeBalancer's hostname, ending with .nodebalancer.linode.com
                    type: string
                  id:
                    type: string
                  ipv4:
                    description: The Public IPv4 Address of this NodeBalancer
                    type: string
                  ipv6:
                    description: The Public IPv6 Address of this NodeBalancer
                    type: string
                  label:
                    description: The label of the Linode NodeBalancer.
                    type: string
                  region:
                    description: The region where this NodeBalancer will be deployed.
                    type: string
                  tags:
                    description: An array of tags applied to this object. Tags are
                      for organizational purposes only.
                    items:
                      type: string
                    type: array
                  transfer:
                    description: Information about the amount of transfer this NodeBalancer
                      has had so far this month.
                    items:
                      properties:
                        in:
                          description: The total transfer, in MB, used by this NodeBalancer
                            this month
                          format: double
                          type: number
                        out:
                          description: The total inbound transfer, in MB, used for
                            this NodeBalancer this month
                          format: double
                          type: number
                        total:
                          description: The total outbound transfer, in MB, used for
                            this NodeBalancer this month
                          format: double
                          type: number
                      type: object
                    type: array
                  updated:
                    description: When this NodeBalancer was last updated.
                    type: string
                required:
                - region
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
