apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: storagebuckets.object.linode.kubeform.com
spec:
  group: object.linode.kubeform.com
  names:
    kind: StorageBucket
    listKind: StorageBucketList
    plural: storagebuckets
    singular: storagebucket
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  accessKey:
                    description: The S3 access key to use for this resource. (Required
                      for lifecycle_rule and versioning)
                    type: string
                  acl:
                    description: The Access Control Level of the bucket using a canned
                      ACL string.
                    type: string
                  cert:
                    description: The cert used by this Object Storage Bucket.
                    type: object
                  cluster:
                    description: The cluster of the Linode Object Storage Bucket.
                    type: string
                  corsEnabled:
                    description: If true, the bucket will be created with CORS enabled
                      for all origins.
                    type: boolean
                  id:
                    type: string
                  label:
                    description: The label of the Linode Object Storage Bucket.
                    type: string
                  lifecycleRule:
                    description: Lifecycle rules to be applied to the bucket.
                    items:
                      properties:
                        ID:
                          description: The unique identifier for the rule.
                          type: string
                        abortIncompleteMultipartUploadDays:
                          description: Specifies the number of days after initiating
                            a multipart upload when the multipart upload must be completed.
                          format: int64
                          type: integer
                        enabled:
                          description: Specifies whether the lifecycle rule is active.
                          type: boolean
                        expiration:
                          description: Specifies a period in the object's expire.
                          properties:
                            date:
                              description: Specifies the date after which you want
                                the corresponding action to take effect.
                              type: string
                            days:
                              description: Specifies the number of days after object
                                creation when the specific rule action takes effect.
                              format: int64
                              type: integer
                            expiredObjectDeleteMarker:
                              description: Directs Linode Object Storage to remove
                                expired deleted markers.
                              type: boolean
                          type: object
                        noncurrentVersionExpiration:
                          description: Specifies when non-current object versions
                            expire.
                          properties:
                            days:
                              description: Specifies the number of days non-current
                                object versions expire.
                              format: int64
                              type: integer
                          required:
                          - days
                          type: object
                        prefix:
                          description: The object key prefix identifying one or more
                            objects to which the rule applies.
                          type: string
                      required:
                      - enabled
                      type: object
                    type: array
                  secretKey:
                    description: The S3 secret key to use for this resource. (Required
                      for lifecycle_rule and versioning)
                    type: string
                  versioning:
                    description: Whether to enable versioning.
                    type: boolean
                required:
                - cluster
                - label
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  accessKey:
                    description: The S3 access key to use for this resource. (Required
                      for lifecycle_rule and versioning)
                    type: string
                  acl:
                    description: The Access Control Level of the bucket using a canned
                      ACL string.
                    type: string
                  cert:
                    description: The cert used by this Object Storage Bucket.
                    type: object
                  cluster:
                    description: The cluster of the Linode Object Storage Bucket.
                    type: string
                  corsEnabled:
                    description: If true, the bucket will be created with CORS enabled
                      for all origins.
                    type: boolean
                  id:
                    type: string
                  label:
                    description: The label of the Linode Object Storage Bucket.
                    type: string
                  lifecycleRule:
                    description: Lifecycle rules to be applied to the bucket.
                    items:
                      properties:
                        ID:
                          description: The unique identifier for the rule.
                          type: string
                        abortIncompleteMultipartUploadDays:
                          description: Specifies the number of days after initiating
                            a multipart upload when the multipart upload must be completed.
                          format: int64
                          type: integer
                        enabled:
                          description: Specifies whether the lifecycle rule is active.
                          type: boolean
                        expiration:
                          description: Specifies a period in the object's expire.
                          properties:
                            date:
                              description: Specifies the date after which you want
                                the corresponding action to take effect.
                              type: string
                            days:
                              description: Specifies the number of days after object
                                creation when the specific rule action takes effect.
                              format: int64
                              type: integer
                            expiredObjectDeleteMarker:
                              description: Directs Linode Object Storage to remove
                                expired deleted markers.
                              type: boolean
                          type: object
                        noncurrentVersionExpiration:
                          description: Specifies when non-current object versions
                            expire.
                          properties:
                            days:
                              description: Specifies the number of days non-current
                                object versions expire.
                              format: int64
                              type: integer
                          required:
                          - days
                          type: object
                        prefix:
                          description: The object key prefix identifying one or more
                            objects to which the rule applies.
                          type: string
                      required:
                      - enabled
                      type: object
                    type: array
                  secretKey:
                    description: The S3 secret key to use for this resource. (Required
                      for lifecycle_rule and versioning)
                    type: string
                  versioning:
                    description: Whether to enable versioning.
                    type: boolean
                required:
                - cluster
                - label
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
