apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: storageobjects.object.linode.kubeform.com
spec:
  group: object.linode.kubeform.com
  names:
    kind: StorageObject
    listKind: StorageObjectList
    plural: storageobjects
    singular: storageobject
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              kubeformOutput:
                properties:
                  accessKey:
                    description: The S3 access key with access to the target bucket.
                    type: string
                  acl:
                    description: The ACL config given to this object.
                    type: string
                  bucket:
                    description: The target bucket to put this object in.
                    type: string
                  cacheControl:
                    description: This cache_control configuration of this object.
                    type: string
                  cluster:
                    description: The target cluster that the bucket is in.
                    type: string
                  content:
                    description: The contents of the Object to upload.
                    type: string
                  contentBase64:
                    description: The base64 contents of the Object to upload.
                    type: string
                  contentDisposition:
                    description: The content disposition configuration of this object.
                    type: string
                  contentEncoding:
                    description: The encoding of the content of this object.
                    type: string
                  contentLanguage:
                    description: The language metadata of this object.
                    type: string
                  contentType:
                    description: The MIME type of the content.
                    type: string
                  etag:
                    description: The specific version of this object.
                    type: string
                  forceDestroy:
                    description: Whether the object should bypass deletion restrictions.
                    type: boolean
                  id:
                    type: string
                  key:
                    description: The name of the uploaded object.
                    type: string
                  metadata:
                    additionalProperties:
                      type: string
                    description: The metadata of this object
                    type: object
                  secretKey:
                    description: The S3 secret key with access to the target bucket.
                    type: string
                  source:
                    description: The source file to upload.
                    type: string
                  versionID:
                    description: The version ID of this object.
                    type: string
                  websiteRedirect:
                    description: The website redirect location of this object.
                    type: string
                required:
                - accessKey
                - bucket
                - cluster
                - key
                - secretKey
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  accessKey:
                    description: The S3 access key with access to the target bucket.
                    type: string
                  acl:
                    description: The ACL config given to this object.
                    type: string
                  bucket:
                    description: The target bucket to put this object in.
                    type: string
                  cacheControl:
                    description: This cache_control configuration of this object.
                    type: string
                  cluster:
                    description: The target cluster that the bucket is in.
                    type: string
                  content:
                    description: The contents of the Object to upload.
                    type: string
                  contentBase64:
                    description: The base64 contents of the Object to upload.
                    type: string
                  contentDisposition:
                    description: The content disposition configuration of this object.
                    type: string
                  contentEncoding:
                    description: The encoding of the content of this object.
                    type: string
                  contentLanguage:
                    description: The language metadata of this object.
                    type: string
                  contentType:
                    description: The MIME type of the content.
                    type: string
                  etag:
                    description: The specific version of this object.
                    type: string
                  forceDestroy:
                    description: Whether the object should bypass deletion restrictions.
                    type: boolean
                  id:
                    type: string
                  key:
                    description: The name of the uploaded object.
                    type: string
                  metadata:
                    additionalProperties:
                      type: string
                    description: The metadata of this object
                    type: object
                  secretKey:
                    description: The S3 secret key with access to the target bucket.
                    type: string
                  source:
                    description: The source file to upload.
                    type: string
                  versionID:
                    description: The version ID of this object.
                    type: string
                  websiteRedirect:
                    description: The website redirect location of this object.
                    type: string
                required:
                - accessKey
                - bucket
                - cluster
                - key
                - secretKey
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
