apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: linode.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: stackscripts.stackscript.linode.kubeform.com
spec:
  group: stackscript.linode.kubeform.com
  names:
    kind: Stackscript
    listKind: StackscriptList
    plural: stackscripts
    singular: stackscript
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  created:
                    description: The date this StackScript was created.
                    type: string
                  deploymentsActive:
                    description: Count of currently active, deployed Linodes created
                      from this StackScript.
                    format: int64
                    type: integer
                  deploymentsTotal:
                    description: The total number of times this StackScript has been
                      deployed.
                    format: int64
                    type: integer
                  description:
                    description: A description for the StackScript.
                    type: string
                  id:
                    type: string
                  images:
                    description: An array of Image IDs representing the Images that
                      this StackScript is compatible for deploying with.
                    items:
                      type: string
                    type: array
                  isPublic:
                    description: This determines whether other users can use your
                      StackScript. Once a StackScript is made public, it cannot be
                      made private.
                    type: boolean
                  label:
                    description: The StackScript's label is for display purposes only.
                    type: string
                  revNote:
                    description: This field allows you to add notes for the set of
                      revisions made to this StackScript.
                    type: string
                  script:
                    description: The script to execute when provisioning a new Linode
                      with this StackScript.
                    type: string
                  updated:
                    description: The date this StackScript was updated.
                    type: string
                  userDefinedFields:
                    description: This is a list of fields defined with a special syntax
                      inside this StackScript that allow for supplying customized
                      parameters during deployment.
                    items:
                      properties:
                        default:
                          description: The default value. If not specified, this value
                            will be used.
                          type: string
                        example:
                          description: An example value for the field.
                          type: string
                        label:
                          description: A human-readable label for the field that will
                            serve as the input prompt for entering the value during
                            deployment.
                          type: string
                        manyOf:
                          description: A list of acceptable values for the field in
                            any quantity, combination or order.
                          type: string
                        name:
                          description: The name of the field.
                          type: string
                        oneOf:
                          description: A list of acceptable single values for the
                            field.
                          type: string
                      type: object
                    type: array
                  userGravatarID:
                    description: The Gravatar ID for the User who created the StackScript.
                    type: string
                  username:
                    description: The User who created the StackScript.
                    type: string
                required:
                - description
                - images
                - label
                - script
                type: object
              state:
                properties:
                  created:
                    description: The date this StackScript was created.
                    type: string
                  deploymentsActive:
                    description: Count of currently active, deployed Linodes created
                      from this StackScript.
                    format: int64
                    type: integer
                  deploymentsTotal:
                    description: The total number of times this StackScript has been
                      deployed.
                    format: int64
                    type: integer
                  description:
                    description: A description for the StackScript.
                    type: string
                  id:
                    type: string
                  images:
                    description: An array of Image IDs representing the Images that
                      this StackScript is compatible for deploying with.
                    items:
                      type: string
                    type: array
                  isPublic:
                    description: This determines whether other users can use your
                      StackScript. Once a StackScript is made public, it cannot be
                      made private.
                    type: boolean
                  label:
                    description: The StackScript's label is for display purposes only.
                    type: string
                  revNote:
                    description: This field allows you to add notes for the set of
                      revisions made to this StackScript.
                    type: string
                  script:
                    description: The script to execute when provisioning a new Linode
                      with this StackScript.
                    type: string
                  updated:
                    description: The date this StackScript was updated.
                    type: string
                  userDefinedFields:
                    description: This is a list of fields defined with a special syntax
                      inside this StackScript that allow for supplying customized
                      parameters during deployment.
                    items:
                      properties:
                        default:
                          description: The default value. If not specified, this value
                            will be used.
                          type: string
                        example:
                          description: An example value for the field.
                          type: string
                        label:
                          description: A human-readable label for the field that will
                            serve as the input prompt for entering the value during
                            deployment.
                          type: string
                        manyOf:
                          description: A list of acceptable values for the field in
                            any quantity, combination or order.
                          type: string
                        name:
                          description: The name of the field.
                          type: string
                        oneOf:
                          description: A list of acceptable single values for the
                            field.
                          type: string
                      type: object
                    type: array
                  userGravatarID:
                    description: The Gravatar ID for the User who created the StackScript.
                    type: string
                  username:
                    description: The User who created the StackScript.
                    type: string
                required:
                - description
                - images
                - label
                - script
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
